kk

diff --git a/.github/workflows/dev-nodejs-pipeline.yaml b/.github/workflows/dev-nodejs-pipeline.yaml
--- a/.github/workflows/dev-nodejs-pipeline.yaml
+++ b/.github/workflows/dev-nodejs-pipeline.yaml
@@ -72,8 +72,40 @@ jobs:
         context: DOCKER_BUILD
         description: ${{ steps.unit_tests.outcome }}  
 
-   #* - name: Security Check (Dependabot + Trivy)
-     
+   #* - name: Security Check (Trivy)
+    - name: Security Check  (Trivy)
+      id: security_check
+      # env:
+      #   GH_TOKEN: ${{ secrets.GH_TOKEN }}
+      shell: bash
+      run: |
+
+        echo "🔍 Running Trivy scan..."
+        trivy image \
+          --scanners vuln \
+          --severity HIGH,CRITICAL,MEDIUM \
+          --pkg-types os \
+          --exit-code 1 \
+          --format table \
+          ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APP_VERSION}
+
+        TRIVY_RESULT=$?
+
+        if [ "$TRIVY_RESULT" -ne 0 ]; then
+          echo "❌ Trivy found vulnerabilities (HIGH/CRITICAL/MEDIUM)"
+          exit 1
+        fi
+
+        echo "✅ Trivy scan passed without blocking issues."    
+
+    - name: Update scan status
+      if: always()
+      uses: tata-actions/workflows/.github/actions/update-commit-status@main
+      with:
+        sha: ${{ github.sha }}
+        state: ${{ steps.security_check.outcome }}     # success / failure / cancelled
+        context: SECURITY_CHECK
+        description: ${{ steps.security_check.outcome }} 
          
 
 
@@ -98,12 +130,12 @@ jobs:
     - name: checkout code #It downloads (clones) your repository code into the runner
       uses: actions/checkout@v6
       with:
-         repository: tata-actions/${{ inputs.component }}-deploy     
+         repository: tata-actions/${{ inputs.project }}/-${{ inputs.component }}-deploys     
 
     - name: deploy to DEV cluster
       id: dev_deploy
       run:
-        "helm upgrade --install ${{ inputs.component}} -f valules-${{ inputs.environment }}.yaml -n ${{ inputs.project }} --set deployment.imageVersion=${APP_VERSION} --atomic --wait --timeout=5m ."
+        "helm upgrade --install ${{ inputs.component}} -f values-${{ inputs.environment }}.yaml -n ${{ inputs.project }} --set deployment.imageVersion=${APP_VERSION} --atomic --wait --timeout=5m ."
 
     - name: Update DEV Deploy status
       if: always()
