ff

diff --git a/.github/workflows/feature-nodejs-pipeline.yaml b/.github/workflows/feature-nodejs-pipeline.yaml
--- a/.github/workflows/feature-nodejs-pipeline.yaml
+++ b/.github/workflows/feature-nodejs-pipeline.yaml
@@ -1,7 +1,6 @@
 name: feature-nodejs-pipeline
-
 on:
-  workflow_call:
+  workflow_call: # will be called by someone, should get inputs from caller
     inputs:
       project:
         required: true
@@ -12,41 +11,35 @@ on:
       environment:
         required: true
         type: string
-
-permissions:
-  contents: read
-  security-events: read 
-  statuses: write   # REQUIRED for Dependabot
-
 env:
-  ACC_ID: 466089068450        
+  ACC_ID: 594171188195        
 
 jobs:
   feature-nodejs-pipeline:
     runs-on: self-hosted
-
     steps:
-    - name: checkout code
-      uses: actions/checkout@v4
-
+    - name: checkout code #It downloads (clones) your repository code into the runner
+      uses: actions/checkout@v6
     - name: list files
       run: ls -l
 
     - name: print inputs
       run: | 
-        echo "project name is ${{ inputs.project }}"
-        echo "project component is ${{ inputs.component }}"    
-        echo "environment is ${{ inputs.environment }}"  
+         echo "project name is ${{ inputs.project }}"
+         echo "project component is ${{ inputs.component }}"    
+         echo "project name is ${{ inputs.environment }}"  
 
     - name: install dependency
       run: npm install
-
+    # we are geting version like commit id first 9 char
     - name: get the version
       run: |
+        # if you store it in GITHUB_ENV, you can use in other steps in the same job we are getting commit id
         echo "APP_VERSION=${GITHUB_SHA::9}" >> "$GITHUB_ENV"
 
-    - name: print version
+    - name: print inputs
       run: |
+        echo ${{ inputs.project }}
         echo "version: ${APP_VERSION}"
 
     - name: run unit test cases
@@ -57,10 +50,11 @@ jobs:
       if: always()
       uses: tata-actions/workflows/.github/actions/update-commit-status@main
       with:
+        # we will pass input to action.yaml (function which proces and call api and update status)
         sha: ${{ github.sha }}
-        state: ${{ steps.unit_tests.outcome }}
+        state: ${{ steps.unit_tests.outcome }}     # success / failure / cancelled
         context: UNIT_TESTS
-        description: ${{ steps.unit_tests.outcome }}
+        description: ${{ steps.unit_tests.outcome }}  
 
     - name: docker build
       id: docker_build
@@ -70,72 +64,22 @@ jobs:
 
     - name: Update docker build status
       if: always()
-      uses: tata-actions/workflows/.github/actions/update-commit-status@main
+      uses: tata-actions/workflows/.github/actions/update-commit-status@main # here will github api and update status against tht commit id
       with:
+        # we will pass input to action.yaml (function which process and call api and update status)
         sha: ${{ github.sha }}
-        state: ${{ steps.docker_build.outcome }}
+        state: ${{ steps.unit_tests.outcome }}     # success / failure / cancelled
         context: DOCKER_BUILD
-        description: ${{ steps.docker_build.outcome }}
+        description: ${{ steps.unit_tests.outcome }}  
 
-    # ✅ Install jq (RHEL)
-    - name: Install jq
-      run: sudo yum install -y jq
-
-    # ✅ Install Trivy (RHEL)
-    - name: Install Trivy
-      run: |
-        sudo yum install -y curl
-        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
-
-    # ✅ Security Gate
     - name: Security Check (Dependabot + Trivy)
       id: security_check
+      # env:
+      #   GH_TOKEN: ${{ secrets.GH_TOKEN }}
       shell: bash
-      env:
-        GH_TOKEN: ${{ secrets.GH_TOKEN }}
-        GITHUB_API: https://api.github.com
-        FULL_REPO: ${{ github.repository }}
       run: |
 
-        echo "Fetching Dependabot alerts..."
-        echo "Repo: ${FULL_REPO}"
-
-        response=$(curl -s \
-          -H "Authorization: Bearer ${GH_TOKEN}" \
-          -H "Accept: application/vnd.github+json" \
-          "${GITHUB_API}/repos/${FULL_REPO}/dependabot/alerts?per_page=100")
-
-        echo "RAW RESPONSE:"
-        echo "${response}"
-
-        # Validate JSON
-        if ! echo "${response}" | jq empty 2>/dev/null; then
-          echo "❌ Invalid JSON response"
-          exit 1
-        fi
-
-        high_critical_open_count=$(echo "${response}" | jq '[.[] 
-          | select(
-              .state == "open" and 
-              (.security_advisory.severity == "high" or .security_advisory.severity == "critical")
-          )
-        ] | length')
-
-        echo "Open HIGH/CRITICAL Dependabot alerts: ${high_critical_open_count}"
-
-        if [ "${high_critical_open_count}" -gt 0 ]; then
-          echo "❌ Blocking pipeline due to vulnerabilities"
-          echo "${response}" | jq '.[] 
-            | select(.state=="open" and 
-            (.security_advisory.severity=="high" or .security_advisory.severity=="critical"))
-            | {dependency: .dependency.package.name, severity: .security_advisory.severity, advisory: .security_advisory.summary}'
-          exit 1
-        else
-          echo "✅ No blocking Dependabot alerts"
-        fi
-
-        echo "Running Trivy scan..."
-
+        echo "🔍 Running Trivy scan..."
         trivy image \
           --scanners vuln \
           --severity HIGH,CRITICAL,MEDIUM \
@@ -144,23 +88,34 @@ jobs:
           --format table \
           ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APP_VERSION}
 
+        TRIVY_RESULT=$?
+
+        if [ "$TRIVY_RESULT" -ne 0 ]; then
+          echo "❌ Trivy found vulnerabilities (HIGH/CRITICAL/MEDIUM)"
+          exit 1
+        fi
+
+        echo "✅ Trivy scan passed without blocking issues."    
+
     - name: Update scan status
       if: always()
       uses: tata-actions/workflows/.github/actions/update-commit-status@main
       with:
         sha: ${{ github.sha }}
-        state: ${{ steps.security_check.outcome }}
+        state: ${{ steps.security_check.outcome }}     # success / failure / cancelled
         context: SECURITY_CHECK
-        description: ${{ steps.security_check.outcome }}
+        description: ${{ steps.security_check.outcome }}        
 
+
+    # reusable workflow cant access sectrects directly we providing again
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v5.1.1
       with:
-        aws-region: us-east-1
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}       
 
     - name: docker push to ecr
-      run: |
-        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com       
-        docker push ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APP_VERSION}
+      run : |
+         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com       
+         docker push ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.project }}/${{ inputs.component }}:${APP_VERSION} align and gv
